#ifndef KTHREAD_SETTINGS_H
#define KTHREAD_SETTINGS_H

#define SWITCH_POLLER_SCHED_POLICY		SCHED_FIFO
#define SWITCH_POLLER_SCHED_PRIORITY		50
#define SWITCH_POLLER_CPU_MASK_BITS		CPU_BITS_ALL

#endif
