IMAGE_INSTALL_append = " \
	networkmanager-config-baselevel \
	sja1105-config-baselevel \
"

# Uncomment the following lines to install the UGW evaluation version to your
# image. Note that you need to copy the binary tarball 'UgwEval.tar' to the
# 'files' directory of the ugw-eval recipe.
# To get a copy of the UGW evaluation binary tarball, please contact us:
#   info@cetitec.com
#

#IMAGE_INSTALL_append = " \
#    ugw-eval \
#    acs-eval \
#"
